### ISSUE TITLE
NextJS Error using hook

### ISSUE THREAD

**Issue by yehorovye** [asplunds/use-ripple#1]
When i try to use this on nextjs 12 react 18 it appears `ReferenceError: document is not defined`

any ideas?

**Comment by asplunds** [comment]
Thanks for bringing this to my attention. I've now added support for ssr/next.

You can install the new version with `npm update use-ripple-hook`

Let me know if this works for you and we can close this issue.

**Comment by yehorovye** [comment]
Thank you so much, i'll make you know if it works!

**Comment by yehorovye** [comment]
UPDATE: It works incredible, thanks for fixing it!
