### ISSUE TITLE
Performance Bug [CRITICAL]

### ISSUE THREAD

**Issue by yehorovye** [asplunds/use-ripple#2]
Every time you click the button, it creates a new ripple container
![image](https://user-images.githubusercontent.com/95551108/174438729-246549e2-dcc4-485a-8458-46eeec0c901f.png)
So if you click button so many times it will lag your website.

**Comment by asplunds** [comment]
Hi, thanks for posting this issue. You're indeed right, after a recent API change the selector that was supposed to select the previous container was missing a dot. This has been fixed now, thank you!

To get the updated version run `npm update use-ripple-hook`

**Comment by yehorovye** [comment]
Thanks again ^^
